name: RESTful API Tests

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'tests/api/restful-api/**'
      - 'src/api/**'
      - 'src/data/restful-api-*'
  pull_request:
    branches: [ main ]
    paths:
      - 'tests/api/restful-api/**'
      - 'src/api/**'
      - 'src/data/restful-api-*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'testing'
        type: choice
        options:
          - testing
          - staging
          - production

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Make scripts executable
      run: chmod +x run-api-tests-nonparallel.sh
    
    - name: Run RESTful API tests
      run: |
        ENV=${{ github.event.inputs.environment || 'testing' }}
        ./run-api-tests-nonparallel.sh $ENV serial 1
      env:
        CI: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: restful-api-test-results
        path: |
          playwright-report/
          test-results/
        retention-days: 30