name: API Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - 'api.config.ts'
      - 'package.json'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - 'api.config.ts'
      - 'package.json'
      - '.github/workflows/api-tests.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'testing'
        type: choice
        options:
          - testing
          - staging
          - production
      test_suite:
        description: 'API test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - restful-booker

jobs:
  api-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
          
      - name: Create environment file
        run: |
          cp .env.example .env.testing
          echo "NODE_ENV=${{ github.event.inputs.environment || 'testing' }}" >> .env.testing
          echo "API_BASE_URL=https://restful-booker.herokuapp.com" >> .env.testing
          echo "CI=true" >> .env.testing

      - name: Run API tests
        env:
          NODE_ENV: ${{ github.event.inputs.environment || 'testing' }}
        run: npm run test:api:serial

      - name: Upload API Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-report
          path: api-report/
          retention-days: 30

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: |
            test-results/api/
            api-results/
          retention-days: 30

  publish-api-report:
    name: Publish API HTML Report
    if: always()
    needs: api-test
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-report
          path: api-report

      - name: Publish HTML Report
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api-report
          destination_dir: api-reports/${{ github.run_number }}

  notify:
    name: Notification
    if: always()
    needs: api-test
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Success
        if: needs.api-test.result == 'success'
        run: echo "✅ All API tests passed successfully!"
        
      - name: Notify on Failure
        if: needs.api-test.result == 'failure'
        run: |
          echo "❌ API Tests failed!"
          echo "Check the test reports for details."
